import "@/styles/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head />
			<body className={cn("font-sans antialiased", inter.className)}>
				<Providers>
					<main className="flex flex-col h-screen bg-muted/50">{children}</main>
				</Providers>
			</body>
		</html>
	);
}
